services:
  - type: web
    name: abuad-farms-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://abuad_farms_db_user:b9WMIgL0uRpp5oEOcrLgHZqTIeZZb48L@dpg-d3at23umcj7s73ef05l0-a/abuad_farms_db
      - key: JWT_SECRET
        value: 8b7ab2189cd79197e57cd98ef6823c4c6c63d6e185781f1e0976baa039e569b318640881d70538e59002419c1c720f99